### ISSUE TITLE
Error: Invalid parameter "prefix"

### ISSUE THREAD

**Issue by pietrzakmat** [stefanscherzinger/cartesian_controllers_universal_robots#2]
Hello,

#### Steps done
I successfully built ros2 branch for cartesian_controllers (all modules) and cartesian_controllers_universal_robots.
I run my ursim_cb3 for UR10 in docker.
Modified: robot.launch.py line 21 to my robot IP:  
"robot_ip", default_value="192.168.56.101", description="The robot's IP address".
In setup.urdf.xacro I changed ur10e to ur10 in relevant lines.

#### Problem

I run: 
```
ros2 launch cartesian_controllers_universal_robots robot.launch.py
```
Output:

```
2 packages had stderr output: cartesian_controller_simulation cartesian_controller_tests
[INFO] [launch]: All log files can be found below /home/mat/.ros/log/2023-12-15-***
[INFO] [launch]: Default logging verbosity is set to INFO
[ERROR] [launch]: Caught exception in launch (see debug for traceback): executed command failed. Command: /opt/ros/humble/bin/xacro ros_ws/install/cartesian_controllers_universal_robots/share/cartesian_controllers_universal_robots/urdf/setup.urdf.xacro robot_ip:=192.168.56.101
Captured stderr output: error: Invalid parameter "prefix"
when instantiating macro: ur_robot (/opt/ros/humble/share/ur_description/urdf/ur_macro.xacro)
in file: ros_ws/install/cartesian_controllers_universal_robots/share/cartesian_controllers_universal_robots/urdf/setup.urdf.xacro
```
#### Software
ROS version: ROS2 humble 
System: Ubuntu 22.04.
Robot: ursim_cb3 with UR10 or actual robot.

Just to mention I get to work successfully github.com/UniversalRobots/Universal_Robots_ROS2_Driver with joint_space_controller by launching following command:
```
ros2 launch ur_robot_driver ur_control.launch.py ur_type:=ur10 robot_ip:=192.168.56.101
```
My goal is to test cartesian controllers on UR10 robot (both ursim and actual robot) in similar way like mentioned ur_robot_driver.
Any suggestion how to proceed?

**Comment by pietrzakmat** [comment]
It was necessary to change  "prefix" to "tf_prefix" in setup.urdf.xacro:
https://github.com/stefanscherzinger/cartesian_controllers_universal_robots/blob/a6b95437c8a11480600c609d4b0c9260581fe214/urdf/setup.urdf.xacro#L17
Closing the issue.

**Comment by stefanscherzinger** [comment]
@pietrzakmat Thanks for spotting and solving this!

If you wish, you could open an PR. I'm happy to merge this.

---
Edit: I'm currently thinking of how to best add an integration test to spot upstream changes in the `ur_description`.
