### ISSUE TITLE
controller unconfigured

### ISSUE THREAD

**Issue by student-0103** [stefanscherzinger/cartesian_controllers_universal_robots#5]
Hi, i got a problem working on the UR5e,
I had done all safety steps and runnen the cartesian_force_controller succesfully on the UR5e. Now, when i do it again i want to deactivate the scaled_joint_trajectory_controller. When I command `ros2 control list_controllers `the following line prints:
```
....
scaled_joint_trajectory_controller[ur_controllers/ScaledJointTrajectoryController] unconfigured
.....
```

All other controller are on active or inactive.
The robot does not do anything.

**Comment by pietrzakmat** [comment]
Hello,
please provide output log after launching robot.launch.py using
`ros2 control list_controllers `.
Normally you should activate and deactivate controllers with following command:
`ros2 control switch_controllers --activate cartesian_force_controller --deactivate scaled_joint_trajectory_controller`
Again share your output log (`ros2 control list_controllers`) after switching controllers.

**Comment by student-0103** [comment]
after launching robot.launch.py:
```
$ ros2 control list_controllers
cartesian_force_controller[cartesian_force_controller/CartesianForceController] inactive  
joint_state_broadcaster[joint_state_broadcaster/JointStateBroadcaster] active    
motion_control_handle[cartesian_controller_handles/MotionControlHandle] inactive  
cartesian_compliance_controller[cartesian_compliance_controller/CartesianComplianceController] inactive  
force_torque_sensor_broadcaster[force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster] active    
cartesian_motion_controller[cartesian_motion_controller/CartesianMotionController] inactive  
scaled_joint_trajectory_controller[ur_controllers/ScaledJointTrajectoryController] unconfigured
```

Then command```
 $ ros2 control switch_controllers --activate cartesian_force_controller --deactivate scaled_joint_trajectory_controller
Successfully switched controllers
``` :
Then again command ros2 control list_controllers :
```
cartesian_force_controller[cartesian_force_controller/CartesianForceController] inactive  
joint_state_broadcaster[joint_state_broadcaster/JointStateBroadcaster] active    
motion_control_handle[cartesian_controller_handles/MotionControlHandle] inactive  
cartesian_compliance_controller[cartesian_compliance_controller/CartesianComplianceController] inactive  
force_torque_sensor_broadcaster[force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster] active    
cartesian_motion_controller[cartesian_motion_controller/CartesianMotionController] inactive  
scaled_joint_trajectory_controller[ur_controllers/ScaledJointTrajectoryController] unconfigured
```
I don't know how/why?



In the terminal from the robot.launch.py it prints this:

[ur_ros2_control_node-2] [WARN] [1705670680.683491322] [controller_manager]: Controller with name 'scaled_joint_trajectory_controller' can not be deactivated since it is not active.
[ur_ros2_control_node-2] [WARN] [1705670680.683547485] [controller_manager]: Could not deactivate controller with name 'scaled_joint_trajectory_controller'. Check above warnings for more details. Check the state of the controllers and their required interfaces using `ros2 control list_controllers -v` CLI to get more information.
[ur_ros2_control_node-2] [ERROR] [1705670680.683744807] [controller_manager]: Resource conflict for controller 'cartesian_force_controller'. Command interface 'shoulder_pan_joint/position' is already claimed.

**Comment by stefanscherzinger** [comment]
@Daan0103

according to your first log output, the `scaled_joint_trajectory_controller` doesn't come up correctly. It should be in state `inactive`, but it's in state `unconfigured`. That's why switching later fails. Could you post the complete output of `robot.launch.py`?

**Comment by pietrzakmat** [comment]
@Daan0103
Based on `controller_manager`  output:
>  Resource conflict for controller 'cartesian_force_controller'. Command interface 'shoulder_pan_joint/position' is already claimed.

it seems like some previously launched processes are still keeping claimed interface. Make sure they're all shut down. Quick way, i.e. reboot your system... Then launch `robot.launch.py ` , `ros2 control list_controllers` and post log output here.

**Comment by student-0103** [comment]
@stefanscherzinger 
My complete output of robot.launch.py:

`$ ros2 launch cartesian_controllers_universal_robots robot.launch.py 
[INFO] [launch]: All log files can be found below /home/viro/.ros/log/2024-01-22-14-53-31-530638-viro-n4451-20466
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [rviz2-1]: process started with pid [20469]
[INFO] [ur_ros2_control_node-2]: process started with pid [20471]
[INFO] [robot_state_publisher-3]: process started with pid [20473]
[INFO] [spawner-4]: process started with pid [20475]
[INFO] [spawner-5]: process started with pid [20477]
[INFO] [spawner-6]: process started with pid [20479]
[INFO] [spawner-7]: process started with pid [20481]
[INFO] [spawner-8]: process started with pid [20483]
[INFO] [spawner-9]: process started with pid [20485]
[INFO] [spawner-10]: process started with pid [20505]
[rviz2-1] Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
[robot_state_publisher-3] [INFO] [1705931612.347135155] [robot_state_publisher]: got segment base
[robot_state_publisher-3] [INFO] [1705931612.347300559] [robot_state_publisher]: got segment base_link
[robot_state_publisher-3] [INFO] [1705931612.347323853] [robot_state_publisher]: got segment base_link_inertia
[robot_state_publisher-3] [INFO] [1705931612.347336756] [robot_state_publisher]: got segment flange
[robot_state_publisher-3] [INFO] [1705931612.347350165] [robot_state_publisher]: got segment forearm_link
[robot_state_publisher-3] [INFO] [1705931612.347361923] [robot_state_publisher]: got segment ft_frame
[robot_state_publisher-3] [INFO] [1705931612.347374896] [robot_state_publisher]: got segment shoulder_link
[robot_state_publisher-3] [INFO] [1705931612.347386553] [robot_state_publisher]: got segment tool0
[robot_state_publisher-3] [INFO] [1705931612.347399571] [robot_state_publisher]: got segment upper_arm_link
[ur_ros2_control_node-2] [WARN] [1705931612.348105295] [controller_manager]: 'update_rate' parameter not set, using default value.
[ur_ros2_control_node-2] [WARN] [1705931612.348257526] [controller_manager]: [Deprecated] Passing the robot description parameter directly to the control_manager node is deprecated. Use '~/robot_description' topic from 'robot_state_publisher' instead.
[ur_ros2_control_node-2] text not specified in the tf_prefix tag
[ur_ros2_control_node-2] [INFO] [1705931612.348929560] [resource_manager]: Loading hardware 'ur5e' 
[ur_ros2_control_node-2] [INFO] [1705931612.352740279] [resource_manager]: Initialize hardware 'ur5e' 
[ur_ros2_control_node-2] [INFO] [1705931612.352856876] [resource_manager]: Successful initialization of hardware 'ur5e'
[ur_ros2_control_node-2] [INFO] [1705931612.353183070] [resource_manager]: 'configure' hardware 'ur5e' 
[ur_ros2_control_node-2] [INFO] [1705931612.353204681] [resource_manager]: Successful 'configure' of hardware 'ur5e'
[ur_ros2_control_node-2] [INFO] [1705931612.353253286] [resource_manager]: 'activate' hardware 'ur5e' 
[ur_ros2_control_node-2] [INFO] [1705931612.353269659] [URPositionHardwareInterface]: Starting ...please wait...
[ur_ros2_control_node-2] [INFO] [1705931612.353292966] [URPositionHardwareInterface]: Initializing driver...
[robot_state_publisher-3] [INFO] [1705931612.355479906] [robot_state_publisher]: got segment world
[robot_state_publisher-3] [INFO] [1705931612.355508096] [robot_state_publisher]: got segment wrist_1_link
[robot_state_publisher-3] [INFO] [1705931612.355527214] [robot_state_publisher]: got segment wrist_2_link
[robot_state_publisher-3] [INFO] [1705931612.355545459] [robot_state_publisher]: got segment wrist_3_link
[ur_ros2_control_node-2] [INFO] [1705931612.360748451] [UR_Client_Library]: SCHED_FIFO OK, priority 99
[ur_ros2_control_node-2] [INFO] [1705931612.561525772] [UR_Client_Library]: Negotiated RTDE protocol version to 2.
[ur_ros2_control_node-2] [INFO] [1705931612.561804524] [UR_Client_Library]: Setting up RTDE communication with frequency 500.000000
[rviz2-1] [INFO] [1705931612.889901003] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-1] [INFO] [1705931612.890129267] [rviz2]: OpenGl version: 4.6 (GLSL 4.6)
[rviz2-1] [INFO] [1705931612.980929282] [rviz2]: Stereo is NOT SUPPORTED
[ur_ros2_control_node-2] [WARN] [1705931613.568490341] [UR_Client_Library]: DEPRECATION NOTICE: Setting the keepalive count has been deprecated. Instead use the RobotReceiveTimeout, to set the timeout directly in the write commands. Please change your code to set the read timeout in the write commands directly. This keepalive count will overwrite the timeout passed to the write functions.
[ur_ros2_control_node-2] [WARN] [1705931613.568517076] [UR_Client_Library]: DEPRECATION NOTICE: Setting the keepalive count has been deprecated. Instead you should set the timeout directly in the write commands. Please change your code to set the read timeout in the write commands directly. This keepalive count will overwrite the timeout passed to the write functions.
[ur_ros2_control_node-2] [INFO] [1705931613.568525185] [URPositionHardwareInterface]: Calibration checksum: 'calib_12788084448423163542'.
[ur_ros2_control_node-2] [ERROR] [1705931614.628958980] [URPositionHardwareInterface]: The calibration parameters of the connected robot don't match the ones from the given kinematics config file. Please be aware that this can lead to critical inaccuracies of tcp positions. Use the ur_calibration tool to extract the correct calibration from the robot and pass that into the description. See [https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/blob/main/ur_calibration/README.md] for details.
[ur_ros2_control_node-2] [INFO] [1705931614.629200335] [URPositionHardwareInterface]: System successfully started!
[ur_ros2_control_node-2] [INFO] [1705931614.629249127] [resource_manager]: Successful 'activate' of hardware 'ur5e'
[ur_ros2_control_node-2] [INFO] [1705931614.660964712] [UR_Client_Library]: SCHED_FIFO OK, priority 99
[ur_ros2_control_node-2] [INFO] [1705931614.794967683] [controller_manager]: Loading controller 'force_torque_sensor_broadcaster'
[spawner-5] [INFO] [1705931614.814918550] [spawner_force_torque_sensor_broadcaster]: Loaded force_torque_sensor_broadcaster
[ur_ros2_control_node-2] [INFO] [1705931614.816458126] [controller_manager]: Loading controller 'joint_state_broadcaster'
[spawner-4] [INFO] [1705931614.837733077] [spawner_joint_state_broadcaster]: Loaded joint_state_broadcaster
[ur_ros2_control_node-2] [INFO] [1705931614.840155722] [controller_manager]: Configuring controller 'joint_state_broadcaster'
[ur_ros2_control_node-2] [INFO] [1705931614.840311686] [joint_state_broadcaster]: 'joints' or 'interfaces' parameter is empty. All available state interfaces will be published
[ur_ros2_control_node-2] [INFO] [1705931614.846899486] [controller_manager]: Loading controller 'cartesian_motion_controller'
[spawner-9] [INFO] [1705931614.874547923] [spawner_cartesian_motion_controller]: Loaded cartesian_motion_controller
[spawner-4] [INFO] [1705931614.875775351] [spawner_joint_state_broadcaster]: Configured and activated joint_state_broadcaster
[ur_ros2_control_node-2] [INFO] [1705931614.876585407] [controller_manager]: Configuring controller 'cartesian_motion_controller'
[ur_ros2_control_node-2] [INFO] [1705931614.885786894] [cartesian_motion_controller]: Forward dynamics solver initialized
[ur_ros2_control_node-2] [INFO] [1705931614.885849722] [cartesian_motion_controller]: Forward dynamics solver has control over 6 joints
[ur_ros2_control_node-2] [INFO] [1705931614.900764940] [controller_manager]: Configuring controller 'force_torque_sensor_broadcaster'
[ur_ros2_control_node-2] [INFO] [1705931614.904878421] [controller_manager]: Loading controller 'motion_control_handle'
[spawner-10] [INFO] [1705931614.937162818] [spawner_motion_control_handle]: Loaded motion_control_handle
[spawner-5] [INFO] [1705931614.937589631] [spawner_force_torque_sensor_broadcaster]: Configured and activated force_torque_sensor_broadcaster
[ur_ros2_control_node-2] [INFO] [1705931614.940156300] [controller_manager]: Configuring controller 'motion_control_handle'
[ur_ros2_control_node-2] [INFO] [1705931614.959646937] [controller_manager]: Loading controller 'cartesian_force_controller'
[ur_ros2_control_node-2] [INFO] [1705931614.989753048] [controller_manager]: Loading controller 'cartesian_compliance_controller'
[spawner-8] [INFO] [1705931614.991304688] [spawner_cartesian_force_controller]: Loaded cartesian_force_controller
[ur_ros2_control_node-2] [INFO] [1705931615.018224964] [controller_manager]: Loading controller 'scaled_joint_trajectory_controller'
[spawner-7] [INFO] [1705931615.020710231] [spawner_cartesian_compliance_controller]: Loaded cartesian_compliance_controller
[ur_ros2_control_node-2] [WARN] [1705931615.054585318] [scaled_joint_trajectory_controller]: [Deprecated]: "allow_nonzero_velocity_at_trajectory_end" is set to true. The default behavior will change to false.
[ur_ros2_control_node-2] [INFO] [1705931615.055250403] [controller_manager]: Configuring controller 'cartesian_compliance_controller'
[spawner-6] [INFO] [1705931615.056671667] [spawner_scaled_joint_trajectory_controller]: Loaded scaled_joint_trajectory_controller
[ur_ros2_control_node-2] [INFO] [1705931615.062762936] [cartesian_compliance_controller]: Forward dynamics solver initialized
[ur_ros2_control_node-2] [INFO] [1705931615.062813600] [cartesian_compliance_controller]: Forward dynamics solver has control over 6 joints
[ur_ros2_control_node-2] [INFO] [1705931615.084603446] [controller_manager]: Configuring controller 'cartesian_force_controller'
[ur_ros2_control_node-2] [INFO] [1705931615.091804886] [cartesian_force_controller]: Forward dynamics solver initialized
[ur_ros2_control_node-2] [INFO] [1705931615.091861148] [cartesian_force_controller]: Forward dynamics solver has control over 6 joints
[ur_ros2_control_node-2] [INFO] [1705931615.097940198] [controller_manager]: Configuring controller 'scaled_joint_trajectory_controller'
[ur_ros2_control_node-2] [INFO] [1705931615.098806805] [scaled_joint_trajectory_controller]: No specific joint names are used for command interfaces. Using 'joints' parameter.
[ur_ros2_control_node-2] [INFO] [1705931615.098873684] [scaled_joint_trajectory_controller]: Command interfaces are [position] and state interfaces are [position velocity].
[ur_ros2_control_node-2] [INFO] [1705931615.099386495] [scaled_joint_trajectory_controller]: Using 'splines' interpolation method.
[ur_ros2_control_node-2] [INFO] [1705931615.101857085] [scaled_joint_trajectory_controller]: Controller state will be published at 100.00 Hz.
[INFO] [spawner-4]: process has finished cleanly [pid 20475]
[ur_ros2_control_node-2] [INFO] [1705931615.107812378] [scaled_joint_trajectory_controller]: Action status changes will be monitored at 20.00 Hz.
[INFO] [spawner-9]: process has finished cleanly [pid 20485]
[INFO] [spawner-5]: process has finished cleanly [pid 20477]
[INFO] [spawner-10]: process has finished cleanly [pid 20505]
[INFO] [spawner-7]: process has finished cleanly [pid 20481]
[ERROR] [ur_ros2_control_node-2]: process has died [pid 20471, exit code -11, cmd '/home/viro/ros2_ws/install/ur_robot_driver/lib/ur_robot_driver/ur_ros2_control_node --ros-args --params-file /tmp/launch_params_sdc3k4mq --params-file /home/viro/ros2_ws/install/cartesian_controllers_universal_robots/share/cartesian_controllers_universal_robots/config/controller_manager.yaml -r motion_control_handle/target_frame:=target_frame -r cartesian_motion_controller/target_frame:=target_frame -r cartesian_compliance_controller/target_frame:=target_frame -r cartesian_force_controller/target_wrench:=target_wrench -r cartesian_compliance_controller/target_wrench:=target_wrench -r cartesian_force_controller/ft_sensor_wrench:=ft_sensor_wrench -r cartesian_compliance_controller/ft_sensor_wrench:=ft_sensor_wrench -r force_torque_sensor_broadcaster/wrench:=ft_sensor_wrench'].
[INFO] [spawner-8]: process has finished cleanly [pid 20483]
`

**Comment by student-0103** [comment]
@pietrzakmat 
After i hit `sudo reboot` and try again:

I did launch it again and in another terminal : `$ ros2 control list_controllers` 
This is the output:
```
cartesian_force_controller[cartesian_force_controller/CartesianForceController] inactive  
joint_state_broadcaster[joint_state_broadcaster/JointStateBroadcaster] active    
scaled_joint_trajectory_controller[ur_controllers/ScaledJointTrajectoryController] unconfigured
cartesian_motion_controller[cartesian_motion_controller/CartesianMotionController] inactive  
force_torque_sensor_broadcaster[force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster] active    
motion_control_handle[cartesian_controller_handles/MotionControlHandle] inactive  
cartesian_compliance_controller[cartesian_compliance_controller/CartesianComplianceController] inactive  
```

**Comment by pietrzakmat** [comment]
Based on your robot.launch.py output your ur_ros2_control_node crashed. 
That node belongs to ur_driver and probably something is wrongly configured or missing.
First I would confirm if ros2 control node of ur_driver is working alone with following call:
`ros2 launch ur_robot_driver ur_control.launch.py ur_type:=ur5e robot_ip:=__robot_ip__ launch_rviz:=false`
Before calling it, terminate any ros launch script that is active. Post output. I expect it to be similar to current outputs, but it will narrow down the search for a cause.

**Comment by student-0103** [comment]
this gives the following output:

$ ros2 launch ur_robot_driver ur_control.launch.py ur_type:=ur5e robot_ip:=192.168.1.102 launch_rviz:=true
[INFO] [launch]: All log files can be found below /home/viro/.ros/log/2024-01-22-16-40-04-126711-viro-n4451-7045
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [dashboard_client-2]: process started with pid [7050]
[INFO] [controller_stopper_node-3]: process started with pid [7052]
[INFO] [ur_ros2_control_node-1]: process started with pid [7048]
[INFO] [robot_state_publisher-4]: process started with pid [7054]
[INFO] [rviz2-5]: process started with pid [7056]
[INFO] [spawner-6]: process started with pid [7058]
[INFO] [spawner-7]: process started with pid [7060]
[INFO] [spawner-8]: process started with pid [7062]
[INFO] [spawner-9]: process started with pid [7064]
[INFO] [spawner-10]: process started with pid [7083]
[INFO] [spawner-11]: process started with pid [7085]
[rviz2-5] Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
[controller_stopper_node-3] [INFO] [1705938005.021553535] [Controller stopper]: Waiting for switch controller service to come up on controller_manager/switch_controller
[robot_state_publisher-4] [INFO] [1705938005.079040388] [robot_state_publisher]: got segment base
[robot_state_publisher-4] [INFO] [1705938005.079212859] [robot_state_publisher]: got segment base_link
[robot_state_publisher-4] [INFO] [1705938005.079236872] [robot_state_publisher]: got segment base_link_inertia
[robot_state_publisher-4] [INFO] [1705938005.079251991] [robot_state_publisher]: got segment flange
[robot_state_publisher-4] [INFO] [1705938005.079266031] [robot_state_publisher]: got segment forearm_link
[robot_state_publisher-4] [INFO] [1705938005.079278969] [robot_state_publisher]: got segment ft_frame
[robot_state_publisher-4] [INFO] [1705938005.079291603] [robot_state_publisher]: got segment shoulder_link
[robot_state_publisher-4] [INFO] [1705938005.079304897] [robot_state_publisher]: got segment tool0
[robot_state_publisher-4] [INFO] [1705938005.079318650] [robot_state_publisher]: got segment upper_arm_link
[robot_state_publisher-4] [INFO] [1705938005.079332211] [robot_state_publisher]: got segment world
[robot_state_publisher-4] [INFO] [1705938005.079345750] [robot_state_publisher]: got segment wrist_1_link
[robot_state_publisher-4] [INFO] [1705938005.079358645] [robot_state_publisher]: got segment wrist_2_link
[robot_state_publisher-4] [INFO] [1705938005.079371828] [robot_state_publisher]: got segment wrist_3_link
[dashboard_client-2] [INFO] [1705938005.083846681] [UR_Client_Library]: Connected: Universal Robots Dashboard Server
[dashboard_client-2] 
[ur_ros2_control_node-1] [WARN] [1705938005.107657506] [controller_manager]: [Deprecated] Passing the robot description parameter directly to the control_manager node is deprecated. Use '~/robot_description' topic from 'robot_state_publisher' instead.
[ur_ros2_control_node-1] text not specified in the tf_prefix tag
[ur_ros2_control_node-1] [INFO] [1705938005.108759225] [resource_manager]: Loading hardware 'ur5e' 
[ur_ros2_control_node-1] [INFO] [1705938005.113194472] [resource_manager]: Initialize hardware 'ur5e' 
[ur_ros2_control_node-1] [INFO] [1705938005.113342902] [resource_manager]: Successful initialization of hardware 'ur5e'
[ur_ros2_control_node-1] [INFO] [1705938005.113671264] [resource_manager]: 'configure' hardware 'ur5e' 
[ur_ros2_control_node-1] [INFO] [1705938005.113703802] [resource_manager]: Successful 'configure' of hardware 'ur5e'
[ur_ros2_control_node-1] [INFO] [1705938005.113762320] [resource_manager]: 'activate' hardware 'ur5e' 
[ur_ros2_control_node-1] [INFO] [1705938005.113778934] [URPositionHardwareInterface]: Starting ...please wait...
[ur_ros2_control_node-1] [INFO] [1705938005.113803765] [URPositionHardwareInterface]: Initializing driver...
[ur_ros2_control_node-1] [INFO] [1705938005.121709952] [UR_Client_Library]: SCHED_FIFO OK, priority 99
[ur_ros2_control_node-1] [INFO] [1705938005.207226899] [UR_Client_Library]: Negotiated RTDE protocol version to 2.
[ur_ros2_control_node-1] [INFO] [1705938005.207523689] [UR_Client_Library]: Setting up RTDE communication with frequency 500.000000
[rviz2-5] [INFO] [1705938005.558900848] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-5] [INFO] [1705938005.559163766] [rviz2]: OpenGl version: 4.6 (GLSL 4.6)
[rviz2-5] [INFO] [1705938005.600629257] [rviz2]: Stereo is NOT SUPPORTED
[ur_ros2_control_node-1] [WARN] [1705938006.232611083] [UR_Client_Library]: DEPRECATION NOTICE: Setting the keepalive count has been deprecated. Instead use the RobotReceiveTimeout, to set the timeout directly in the write commands. Please change your code to set the read timeout in the write commands directly. This keepalive count will overwrite the timeout passed to the write functions.
[ur_ros2_control_node-1] [WARN] [1705938006.232682055] [UR_Client_Library]: DEPRECATION NOTICE: Setting the keepalive count has been deprecated. Instead you should set the timeout directly in the write commands. Please change your code to set the read timeout in the write commands directly. This keepalive count will overwrite the timeout passed to the write functions.
[ur_ros2_control_node-1] [INFO] [1705938006.232694312] [URPositionHardwareInterface]: Calibration checksum: 'calib_12788084448423163542'.
[ur_ros2_control_node-1] [ERROR] [1705938007.260701599] [URPositionHardwareInterface]: The calibration parameters of the connected robot don't match the ones from the given kinematics config file. Please be aware that this can lead to critical inaccuracies of tcp positions. Use the ur_calibration tool to extract the correct calibration from the robot and pass that into the description. See [https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/blob/main/ur_calibration/README.md] for details.
[ur_ros2_control_node-1] [INFO] [1705938007.260847734] [URPositionHardwareInterface]: System successfully started!
[ur_ros2_control_node-1] [INFO] [1705938007.260918313] [resource_manager]: Successful 'activate' of hardware 'ur5e'
[controller_stopper_node-3] [INFO] [1705938007.270762506] [Controller stopper]: Service available
[controller_stopper_node-3] [INFO] [1705938007.270804802] [Controller stopper]: Waiting for list controllers service to come up on controller_manager/list_controllers
[controller_stopper_node-3] [INFO] [1705938007.270836616] [Controller stopper]: Service available
[ur_ros2_control_node-1] [INFO] [1705938007.277432257] [UR_Client_Library]: SCHED_FIFO OK, priority 99
[ur_ros2_control_node-1] [INFO] [1705938007.394574952] [controller_manager]: Loading controller 'forward_position_controller'
[spawner-11] [INFO] [1705938007.426351122] [spawner_forward_position_controller]: Loaded forward_position_controller
[ur_ros2_control_node-1] [INFO] [1705938007.431229558] [controller_manager]: Configuring controller 'forward_position_controller'
[ur_ros2_control_node-1] [INFO] [1705938007.435252154] [forward_position_controller]: configure successful
[ur_ros2_control_node-1] [INFO] [1705938007.436958884] [controller_manager]: Loading controller 'joint_state_broadcaster'
[ur_ros2_control_node-1] [INFO] [1705938007.462284646] [controller_manager]: Loading controller 'force_torque_sensor_broadcaster'
[spawner-7] [INFO] [1705938007.463006740] [spawner_joint_state_broadcaster]: Loaded joint_state_broadcaster
[ur_ros2_control_node-1] [INFO] [1705938007.482513368] [controller_manager]: Loading controller 'speed_scaling_state_broadcaster'
[spawner-10] [INFO] [1705938007.483619264] [spawner_force_torque_sensor_broadcaster]: Loaded force_torque_sensor_broadcaster
[ur_ros2_control_node-1] [INFO] [1705938007.509608505] [speed_scaling_state_broadcaster]: Loading UR SpeedScalingStateBroadcaster with tf_prefix: 
[ur_ros2_control_node-1] [INFO] [1705938007.510524157] [controller_manager]: Loading controller 'io_and_status_controller'
[spawner-9] [INFO] [1705938007.518247044] [spawner_speed_scaling_state_broadcaster]: Loaded speed_scaling_state_broadcaster
[ur_ros2_control_node-1] [INFO] [1705938007.535977882] [controller_manager]: Configuring controller 'joint_state_broadcaster'
[ur_ros2_control_node-1] [INFO] [1705938007.536109273] [joint_state_broadcaster]: 'joints' or 'interfaces' parameter is empty. All available state interfaces will be published
[spawner-8] [INFO] [1705938007.536438255] [spawner_io_and_status_controller]: Loaded io_and_status_controller
[ur_ros2_control_node-1] [INFO] [1705938007.548283388] [controller_manager]: Loading controller 'scaled_joint_trajectory_controller'
[ur_ros2_control_node-1] [WARN] [1705938007.580045406] [scaled_joint_trajectory_controller]: [Deprecated]: "allow_nonzero_velocity_at_trajectory_end" is set to true. The default behavior will change to false.
[ur_ros2_control_node-1] [INFO] [1705938007.581195749] [controller_manager]: Configuring controller 'force_torque_sensor_broadcaster'
[spawner-6] [INFO] [1705938007.583262509] [spawner_scaled_joint_trajectory_controller]: Loaded scaled_joint_trajectory_controller
[ur_ros2_control_node-1] [INFO] [1705938007.586057080] [controller_manager]: Configuring controller 'speed_scaling_state_broadcaster'
[ur_ros2_control_node-1] [INFO] [1705938007.586280740] [speed_scaling_state_broadcaster]: Publisher rate set to : 100.0 Hz
[ur_ros2_control_node-1] [INFO] [1705938007.593818158] [controller_manager]: Configuring controller 'io_and_status_controller'
[ur_ros2_control_node-1] [INFO] [1705938007.594038601] [io_and_status_controller]: Configure UR gpio controller with tf_prefix: 
[ur_ros2_control_node-1] [INFO] [1705938007.594201523] [io_and_status_controller]: Configure UR gpio controller with tf_prefix: 
[ur_ros2_control_node-1] [INFO] [1705938007.596537601] [io_and_status_controller]: Configure UR gpio controller with tf_prefix: 
[ur_ros2_control_node-1] [INFO] [1705938007.596919950] [controller_manager]: Configuring controller 'scaled_joint_trajectory_controller'
[ur_ros2_control_node-1] [INFO] [1705938007.597193923] [scaled_joint_trajectory_controller]: No specific joint names are used for command interfaces. Using 'joints' parameter.
[ur_ros2_control_node-1] [INFO] [1705938007.597256148] [scaled_joint_trajectory_controller]: Command interfaces are [position] and state interfaces are [position velocity].
[ur_ros2_control_node-1] [INFO] [1705938007.597285796] [scaled_joint_trajectory_controller]: Using 'splines' interpolation method.
[ur_ros2_control_node-1] [INFO] [1705938007.599221379] [scaled_joint_trajectory_controller]: Controller state will be published at 100.00 Hz.
[ur_ros2_control_node-1] [INFO] [1705938007.603242923] [scaled_joint_trajectory_controller]: Action status changes will be monitored at 20.00 Hz.
[ur_ros2_control_node-1] [INFO] [1705938007.615141152] [io_and_status_controller]: Configure UR gpio controller with tf_prefix: 
[ur_ros2_control_node-1] [INFO] [1705938007.615354569] [io_and_status_controller]: Configure UR gpio controller with tf_prefix: 
[ur_ros2_control_node-1] [INFO] [1705938007.615576759] [io_and_status_controller]: Configure UR gpio controller with tf_prefix: 
[ur_ros2_control_node-1] [INFO] [1705938007.618235328] [io_and_status_controller]: Configure UR gpio controller with tf_prefix: 
[ur_ros2_control_node-1] [INFO] [1705938007.620324715] [io_and_status_controller]: Configure UR gpio controller with tf_prefix: 
[spawner-7] [INFO] [1705938007.621859259] [spawner_joint_state_broadcaster]: Configured and activated joint_state_broadcaster
[ur_ros2_control_node-1] [INFO] [1705938007.622790300] [io_and_status_controller]: Configure UR gpio controller with tf_prefix: 
[ur_ros2_control_node-1] [INFO] [1705938007.624051396] [io_and_status_controller]: Configure UR gpio controller with tf_prefix: 
[ur_ros2_control_node-1] [INFO] [1705938007.625259796] [io_and_status_controller]: Configure UR gpio controller with tf_prefix: 
[ur_ros2_control_node-1] [INFO] [1705938007.626161520] [io_and_status_controller]: Configure UR gpio controller with tf_prefix: 
[ur_ros2_control_node-1] [INFO] [1705938007.626476408] [io_and_status_controller]: Configure UR gpio controller with tf_prefix: 
[spawner-10] [INFO] [1705938007.625937593] [spawner_force_torque_sensor_broadcaster]: Configured and activated force_torque_sensor_broadcaster
[ur_ros2_control_node-1] [INFO] [1705938007.626587757] [io_and_status_controller]: Configure UR gpio controller with tf_prefix: 
[ur_ros2_control_node-1] [INFO] [1705938007.626784719] [io_and_status_controller]: Configure UR gpio controller with tf_prefix: 
[INFO] [spawner-11]: process has finished cleanly [pid 7085]
[ur_ros2_control_node-1] [INFO] [1705938007.662267357] [io_and_status_controller]: Configure UR gpio controller with tf_prefix: 
[ur_ros2_control_node-1] [INFO] [1705938007.663265975] [io_and_status_controller]: Configure UR gpio controller with tf_prefix: 
[spawner-8] [INFO] [1705938007.664714471] [spawner_io_and_status_controller]: Configured and activated io_and_status_controller
[ERROR] [ur_ros2_control_node-1]: process has died [pid 7048, exit code -11, cmd '/home/viro/ros2_ws/install/ur_robot_driver/lib/ur_robot_driver/ur_ros2_control_node --ros-args --params-file /tmp/launch_params_aenxvt0n --params-file /home/viro/ros2_ws/install/ur_robot_driver/share/ur_robot_driver/config/ur5e_update_rate.yaml --params-file /home/viro/ros2_ws/install/ur_robot_driver/share/ur_robot_driver/config/ur_controllers.yaml'].
[INFO] [spawner-7]: process has finished cleanly [pid 7060]
[INFO] [spawner-10]: process has finished cleanly [pid 7083]
[INFO] [spawner-8]: process has finished cleanly [pid 7062]
`
`

**Comment by pietrzakmat** [comment]
The line:
`[ERROR] [ur_ros2_control_node-1]: process has died [pid 7048, exit code -11, cmd '/home/viro/ros2_ws/install/ur_robot_driver/lib/ur_robot_driver/ur_ros2_control_node --ros-args --params-file /tmp/launch_params_aenxvt0n --params-file /home/viro/ros2_ws/install/ur_robot_driver/share/ur_robot_driver/config/ur5e_update_rate.yaml --params-file /home/viro/ros2_ws/install/ur_robot_driver/share/ur_robot_driver/config/ur_controllers.yaml'].`
indicates the problem with ros2 control part of ur_driver. Seems like some parameters are incorrect or loaded wrongly. 

Without too much digging I would reinstall the driver. Preferably build& install from source:
 [https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver](url) 
You may try it. Unless some parameters from above are modified intentionally by you for some reason.

**Comment by student-0103** [comment]
Hi @pietrzakmat 
I deleted the ur_driver and installed it again from source. With a clean build, the output is as follows:
```
$ ros2 control list_controllers
force_torque_sensor_broadcaster[force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster] active    
scaled_joint_trajectory_controller[ur_controllers/ScaledJointTrajectoryController] active    
joint_state_broadcaster[joint_state_broadcaster/JointStateBroadcaster] active    
cartesian_compliance_controller[cartesian_compliance_controller/CartesianComplianceController] inactive  
cartesian_force_controller[cartesian_force_controller/CartesianForceController] inactive  
motion_control_handle[cartesian_controller_handles/MotionControlHandle] inactive  
cartesian_motion_controller[cartesian_motion_controller/CartesianMotionController] inactive `
```
`
The problem was somewhere inside this package..
Thanks for your help! Preciate it.

**Comment by pietrzakmat** [comment]
@Daan0103,
I'm glad to hear that it works for you now.
As I do not have permissions for the repo, please close the issue.
